test_0 (__main__.lab5a.test_0)
[Lab 5] - [Investigation 1] - [Part 1] - Files - Test for file creation: ./lab5a.py ... ok
test_a (__main__.lab5a.test_a)
[Lab 5] - [Investigation 1] - [Part 1] - Files - Test for errors running: ./lab5a.py ... ok
test_a1 (__main__.lab5a.test_a1)
[Lab 5] - [Investigation 1] - [Part 1] - Files - Test for correct shebang line: ./lab5a.py ... ok
test_a_function_read_file_string (__main__.lab5a.test_a_function_read_file_string)
[Lab 5] - [Investigation 1] - [Part 1] - Files - function read_file_string fails without 1 argument ... ok
test_b_function_read_file_list (__main__.lab5a.test_b_function_read_file_list)
[Lab 5] - [Investigation 1] - [Part 1] - Files - function read_file_list fails without 1 argument ... ok
test_c_file_data_txt_exists (__main__.lab5a.test_c_file_data_txt_exists)
[Lab 5] - [Investigation 1] - [Part 1] - Files - Test for file creation: ./data.txt ... ok
test_d_file_data_txt_has_correct_text (__main__.lab5a.test_d_file_data_txt_has_correct_text)
[Lab 5] - [Investigation 1] - [Part 1] - Files - Test for correct contents: ./data.txt ... ok
test_e_function_read_file_string_correct_output (__main__.lab5a.test_e_function_read_file_string_correct_output)
[Lab 5] - [Investigation 1] - [Part 1] - Files - Test for output: ./lab5a.py ... ok
test_f_function_read_file_list_correct_output (__main__.lab5a.test_f_function_read_file_list_correct_output)
[Lab 5] - [Investigation 1] - [Part 1] - Files - Test for output: ./lab5a.py ... ok
test_g_function_read_file_list_correct_output (__main__.lab5a.test_g_function_read_file_list_correct_output)
[Lab 5] - [Investigation 1] - [Part 1] - Files - Test for output: ./lab5a.py ... ok
test_h_function_read_file_list_correct_output (__main__.lab5a.test_h_function_read_file_list_correct_output)
[Lab 5] - [Investigation 1] - [Part 1] - Files - Test for output: ./lab5a.py ... ok
test_0 (__main__.lab5b.test_0)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for file creation: ./lab5b.py ... ok
test_a (__main__.lab5b.test_a)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for errors running: ./lab5b.py ... ok
test_a1 (__main__.lab5b.test_a1)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for correct shebang line: ./lab5b.py ... ok
test_a_function_append_file_string (__main__.lab5b.test_a_function_append_file_string)
[Lab 5] - [Investigation 1] - [Part 2] - Files - function append_file_string fails without 2 argument ... ok
test_a_function_read_file_string (__main__.lab5b.test_a_function_read_file_string)
[Lab 5] - [Investigation 1] - [Part 2] - Files - function read_file_string fails without 1 argument ... ok
test_b_function_read_file_list (__main__.lab5b.test_b_function_read_file_list)
[Lab 5] - [Investigation 1] - [Part 2] - Files - function read_file_list fails without 1 argument ... ok
test_c_function_write_file_list (__main__.lab5b.test_c_function_write_file_list)
[Lab 5] - [Investigation 1] - [Part 2] - Files - function write_file_list fails without 2 argument ... ok
test_d_function_copy_file_add_line_numbers (__main__.lab5b.test_d_function_copy_file_add_line_numbers)
[Lab 5] - [Investigation 1] - [Part 2] - Files - function copy_file_add_line_numbers fails without 2 argument ... ok
test_e_file_data_txt_exists (__main__.lab5b.test_e_file_data_txt_exists)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for file creation: ./data.txt ... ok
test_f_file_data_txt_has_correct_text (__main__.lab5b.test_f_file_data_txt_has_correct_text)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for correct contents: ./data.txt ... ok
test_g_function_read_file_string_correct_output (__main__.lab5b.test_g_function_read_file_string_correct_output)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py ... ok
test_h_function_read_file_list_correct_output (__main__.lab5b.test_h_function_read_file_list_correct_output)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py ... ok
test_i_function_append_file_string_correct_output_1 (__main__.lab5b.test_i_function_append_file_string_correct_output_1)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py ... FAIL
test_i_function_append_file_string_correct_output_2 (__main__.lab5b.test_i_function_append_file_string_correct_output_2)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py ... FAIL
test_j_function_write_file_list_correct_output_1 (__main__.lab5b.test_j_function_write_file_list_correct_output_1)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py ... /home/fraj/ops445/lab5/./CheckLab5.py:262: ResourceWarning: unclosed file <_io.TextIOWrapper name='seneca2.txt.checkscript' mode='w' encoding='UTF-8'>
  lab5bStudent.write_file_list(filename, list1)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok
test_j_function_write_file_list_correct_output_2 (__main__.lab5b.test_j_function_write_file_list_correct_output_2)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py ... /home/fraj/ops445/lab5/./CheckLab5.py:277: ResourceWarning: unclosed file <_io.TextIOWrapper name='seneca2.txt.checkscript' mode='w' encoding='UTF-8'>
  lab5bStudent.write_file_list(filename, list1)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/fraj/ops445/lab5/./CheckLab5.py:278: ResourceWarning: unclosed file <_io.TextIOWrapper name='seneca2.txt.checkscript' mode='w' encoding='UTF-8'>
  lab5bStudent.write_file_list(filename, list1)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok
test_k_function_copy_file_add_line_numbers_correct_output_1 (__main__.lab5b.test_k_function_copy_file_add_line_numbers_correct_output_1)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py ... /home/fraj/ops445/lab5/./CheckLab5.py:293: ResourceWarning: unclosed file <_io.TextIOWrapper name='seneca2.txt.checkscript' mode='r' encoding='UTF-8'>
  lab5bStudent.copy_file_add_line_numbers(filename, tempfile)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/fraj/ops445/lab5/./CheckLab5.py:293: ResourceWarning: unclosed file <_io.TextIOWrapper name='seneca3.txt.checkscript' mode='a' encoding='UTF-8'>
  lab5bStudent.copy_file_add_line_numbers(filename, tempfile)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
FAIL
test_k_function_copy_file_add_line_numbers_correct_output_2 (__main__.lab5b.test_k_function_copy_file_add_line_numbers_correct_output_2)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py ... /home/fraj/ops445/lab5/./CheckLab5.py:308: ResourceWarning: unclosed file <_io.TextIOWrapper name='seneca2.txt.checkscript' mode='r' encoding='UTF-8'>
  lab5bStudent.copy_file_add_line_numbers(filename, tempfile)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/fraj/ops445/lab5/./CheckLab5.py:308: ResourceWarning: unclosed file <_io.TextIOWrapper name='seneca3.txt.checkscript' mode='a' encoding='UTF-8'>
  lab5bStudent.copy_file_add_line_numbers(filename, tempfile)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/fraj/ops445/lab5/./CheckLab5.py:309: ResourceWarning: unclosed file <_io.TextIOWrapper name='seneca2.txt.checkscript' mode='r' encoding='UTF-8'>
  lab5bStudent.copy_file_add_line_numbers(filename, tempfile)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/fraj/ops445/lab5/./CheckLab5.py:309: ResourceWarning: unclosed file <_io.TextIOWrapper name='seneca3.txt.checkscript' mode='a' encoding='UTF-8'>
  lab5bStudent.copy_file_add_line_numbers(filename, tempfile)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
FAIL
test_k_function_copy_file_add_line_numbers_correct_output_3 (__main__.lab5b.test_k_function_copy_file_add_line_numbers_correct_output_3)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py ... /home/fraj/ops445/lab5/./CheckLab5.py:322: ResourceWarning: unclosed file <_io.TextIOWrapper name='seneca3.txt.checkscript' mode='r' encoding='UTF-8'>
  lab5bStudent.copy_file_add_line_numbers(filename, tempfile)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/fraj/ops445/lab5/./CheckLab5.py:322: ResourceWarning: unclosed file <_io.TextIOWrapper name='seneca4.txt.checkscript' mode='a' encoding='UTF-8'>
  lab5bStudent.copy_file_add_line_numbers(filename, tempfile)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
FAIL
test_0 (__main__.lab5c.test_0)
[Lab 5] - [Investigation 2] - [Part 1] - Files - Test for file creation: ./lab5c.py ... ok
test_a (__main__.lab5c.test_a)
[Lab 5] - [Investigation 2] - [Part 1] - Files - Test for errors running: ./lab5c.py ... ok
test_a1 (__main__.lab5c.test_a1)
[Lab 5] - [Investigation 2] - [Part 1] - Files - Test for correct shebang line: ./lab5c.py ... ok
test_a_function_add (__main__.lab5c.test_a_function_add)
[Lab 5] - [Investigation 2] - [Part 1] - Files - function add fails without 2 argument ... ok
test_b_function_read_file (__main__.lab5c.test_b_function_read_file)
[Lab 5] - [Investigation 2] - [Part 1] - Files - function read_file fails without 1 argument ... ok
test_c_function_add_correct_output_1 (__main__.lab5c.test_c_function_add_correct_output_1)
[Lab 5] - [Investigation 2] - [Part 1] - Files - Test for output: ./lab5c.py ... ok
test_c_function_add_correct_output_2 (__main__.lab5c.test_c_function_add_correct_output_2)
[Lab 5] - [Investigation 2] - [Part 1] - Files - Test for output: ./lab5c.py ... ok
test_c_function_add_correct_output_3 (__main__.lab5c.test_c_function_add_correct_output_3)
[Lab 5] - [Investigation 2] - [Part 1] - Files - Test for output: ./lab5c.py ... ok
test_c_function_add_correct_output_4 (__main__.lab5c.test_c_function_add_correct_output_4)
[Lab 5] - [Investigation 2] - [Part 1] - Files - Test for output: ./lab5c.py ... ok
test_d_function_read_file_correct_output_1 (__main__.lab5c.test_d_function_read_file_correct_output_1)
[Lab 5] - [Investigation 2] - [Part 1] - Files - Test for output: ./lab5c.py ... ok
test_d_function_read_file_correct_output_2 (__main__.lab5c.test_d_function_read_file_correct_output_2)
[Lab 5] - [Investigation 2] - [Part 1] - Files - Test for output: ./lab5c.py ... ok

======================================================================
FAIL: test_i_function_append_file_string_correct_output_1 (__main__.lab5b.test_i_function_append_file_string_correct_output_1)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fraj/ops445/lab5/./CheckLab5.py", line 232, in test_i_function_append_file_string_correct_output_1
    self.assertEqual(lab5bStudent.read_file_string(filename), answer, msg=error_output)
AssertionError: 'First Line\nSecond Line\nThird Line\n\nFirst Line\nSecond Line\nThird Line\n\n' != 'First Line\nSecond Line\nThird Line\nFirst Line\nSecond Line\nThird Line\n'
  First Line
  Second Line
  Third Line
- 
  First Line
  Second Line
  Third Line
- 
 : incorrect output(HINT: make sure function is appending and not overwriting)

======================================================================
FAIL: test_i_function_append_file_string_correct_output_2 (__main__.lab5b.test_i_function_append_file_string_correct_output_2)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fraj/ops445/lab5/./CheckLab5.py", line 248, in test_i_function_append_file_string_correct_output_2
    self.assertEqual(lab5bStudent.read_file_string(filename), answer, msg=error_output)
AssertionError: 'First Line\nSecond Line\nThird\n\nFirst Line\nSecond Line\nThird\n\n' != 'First Line\nSecond Line\nThird\nFirst Line\nSecond Line\nThird\n'
  First Line
  Second Line
  Third
- 
  First Line
  Second Line
  Third
- 
 : incorrect output(HINT: make sure function is appending and not overwriting)

======================================================================
FAIL: test_k_function_copy_file_add_line_numbers_correct_output_1 (__main__.lab5b.test_k_function_copy_file_add_line_numbers_correct_output_1)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fraj/ops445/lab5/./CheckLab5.py", line 295, in test_k_function_copy_file_add_line_numbers_correct_output_1
    self.assertEqual(lab5bStudent.read_file_string(tempfile), answer, msg=error_output)
AssertionError: '1: Line 1\n2: Line 2\n3: Line 5\n' != '1:Line 1\n2:Line 2\n3:Line 5\n'
- 1: Line 1
?   -
+ 1:Line 1
- 2: Line 2
?   -
+ 2:Line 2
- 3: Line 5
?   -
+ 3:Line 5
 : incorrect output(HINT: make sure output shows exactly)

======================================================================
FAIL: test_k_function_copy_file_add_line_numbers_correct_output_2 (__main__.lab5b.test_k_function_copy_file_add_line_numbers_correct_output_2)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fraj/ops445/lab5/./CheckLab5.py", line 311, in test_k_function_copy_file_add_line_numbers_correct_output_2
    self.assertEqual(lab5bStudent.read_file_string(tempfile), answer, msg=error_output)
AssertionError: '1: Line 1\n2: Line 2\n3: Line 5\n1: Line 1\n2: Line 2\n3: Line 5\n' != '1:Line 1\n2:Line 2\n3:Line 5\n'
- 1: Line 1
?   -
+ 1:Line 1
- 2: Line 2
?   -
+ 2:Line 2
- 3: Line 5
?   -
+ 3:Line 5
- 1: Line 1
- 2: Line 2
- 3: Line 5
 : incorrect output(HINT: make sure to write to file NOT append )

======================================================================
FAIL: test_k_function_copy_file_add_line_numbers_correct_output_3 (__main__.lab5b.test_k_function_copy_file_add_line_numbers_correct_output_3)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fraj/ops445/lab5/./CheckLab5.py", line 324, in test_k_function_copy_file_add_line_numbers_correct_output_3
    self.assertEqual(lab5bStudent.read_file_string(tempfile), answer, msg=error_output)
AssertionError: '1: 1: Line 1\n2: 2: Line 2\n3: 3: Line 5\n4[37 chars] 5\n' != '1:1:Line 1\n2:2:Line 2\n3:3:Line 5\n'
- 1: 1: Line 1
?   -  -
+ 1:1:Line 1
- 2: 2: Line 2
?   -  -
+ 2:2:Line 2
- 3: 3: Line 5
?   -  -
+ 3:3:Line 5
- 4: 1: Line 1
- 5: 2: Line 2
- 6: 3: Line 5
 : incorrect output(HINT: read instructions again and confirm code follows correctly)

----------------------------------------------------------------------
Ran 41 tests in 0.029s

FAILED (failures=5)
